---
# tasks file for role_bi_selinux
- name: Include os independent variables.
  include_vars: "vars/main.yml"

- name: Initial set of variables
  debug:
    msg: '{{ lookup("vars", item) }}'
  loop: '{{ lookup("varnames", role_name).split(",") }}'

- name: Configure role_bi_selinux
  include: 02-configure.yml

- name: Unset all role variables
  include: 81-cleanup-vars.yml

- name: Final set of variables
  debug:
    msg: '{{ lookup("vars", item) }}'
  loop: '{{ lookup("varnames", role_name).split(",") }}'

